name: Build LudoUltimate APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev \
            libpng-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev

          pip install --upgrade pip
          pip install cython virtualenv

      - name: Build APK using Buildozer
        run: |
          pip install buildozer
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: LudoUltimate-APK
          path: bin/*.apk
